# Generated by Django 3.2.4 on 2021-06-20 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='overall_rating',
            field=models.FloatField(default=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='overall_review',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
