# Generated by Django 3.2.4 on 2021-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0003_alter_application_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='overall_review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
