# Generated by Django 3.2.4 on 2021-06-20 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0004_alter_application_overall_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='overall_rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(2)]),
        ),
    ]
